### ISSUE TITLE
Comments end

### ISSUE THREAD

**Issue by Imadra** [philbot9/youtube-comment-api#1]
How to know that comments are shown completely so I can start another operation with all comments of a video?

**Comment by philbot9** [comment]
Hi there,
You can tell that you have received the last page of comments when there is no "nextPageToken" in the response. 

Please note that this project currently uses an older iteration of the YouTube comment system. There appears to be a bug where on some videos the last page may still contain a "nextPageToken". In that case I believe fetching a page with that token will fail.

There's an issue for this here:
https://github.com/philbot9/youtube-comments-task/issues/3
